package com.ilearnrw.services.datalogger;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The LogFilter class is used to query the Datalogger
 * for log entries.
 * 
 * The LogFilter
 */
public class LogFilter implements Serializable {

	private static final long serialVersionUID = -7085054143765991532L;

	@JsonProperty("token")
	private String token;

	/**
	 * The user-id for the user that the particular log
	 * concerns.
	 */
	@JsonProperty("userId")
	private String userId;
	
	/**
	 * A tag for the LogEntry.
	 */
	@JsonProperty("tags")
	private List<String> tags;
	
	/**
	 * An application identifier.
	 */
	@JsonProperty("applicationId")
	private String applicationId;
	
	public void setApplicationId(String newId)
	{
		applicationId = newId;
	}
	

	@JsonProperty("timestart")
	private Timestamp timestart;

	@JsonProperty("timeend")
	private Timestamp timeend;
	
	/**
	 * A sessionId.
	 * 
	 * The sessionId would be generated by the client to identify
	 * a specific session.
	 * 
	 */
	@JsonProperty("sessionId")
	private String sessionId;
	
	

}
